### ISSUE TITLE
Site Interventions Release

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#199]
* [x] Version 25 for Firefox 92 (Soft Freeze: 2021-08-05) - @karlcow - [Bugzilla Bug #1720138](https://bugzilla.mozilla.org/show_bug.cgi?id=1720138)
* [x] Version 26 for Firefox 93 (Soft Freeze: 2021-09-02) - @ksy36 - [Bugzilla Bug #1720139](https://bugzilla.mozilla.org/show_bug.cgi?id=1720139)
* [x] Version 27 for Firefox 94 (Soft Freeze: 2021-09-30) - @wisniewskit - [Bugzilla Bug #1720140](https://bugzilla.mozilla.org/show_bug.cgi?id=1720140)
* [x] Version 28 for Firefox 95 (Soft Freeze: 2021-10-28) - @denschub - [Bugzilla Bug #1720142](https://bugzilla.mozilla.org/show_bug.cgi?id=1720142)
* [x] Version 29 for Firefox 96 (Soft Freeze: 2021-12-02) - @karlcow - [Bugzilla Bug #1720143](https://bugzilla.mozilla.org/show_bug.cgi?id=1720143)

**Comment by softvision-oana-arbuzov** [comment]
1st QA run (Q3) - 2021-07-22

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st run (Q3) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=6586243

UA Overrides to be removed:
[1721835](https://bugzilla.mozilla.org/show_bug.cgi?id=1721835) Remove UA Override for automotivesuperstore.com.au

**Comment by softvision-oana-arbuzov** [comment]
2nd QA run (Q3) - 2021-08-19

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd run (Q3) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1732552367

UA Overrides to be removed:
[1726520](https://bugzilla.mozilla.org/show_bug.cgi?id=1726520) Remove UA Override for corporate.santander.co.uk
[1726542](https://bugzilla.mozilla.org/show_bug.cgi?id=1726542) Remove UA Override for gouletpens.com
[1726545](https://bugzilla.mozilla.org/show_bug.cgi?id=1726545) Remove UA Override for posts.google.com

Interventions to be removed:
[1726555](https://bugzilla.mozilla.org/show_bug.cgi?id=1726555) Remove Intervention for gaana.com
[1726558](https://bugzilla.mozilla.org/show_bug.cgi?id=1726558) Remove Intervention for snaptik.app

**Comment by softvision-oana-arbuzov** [comment]
3rd QA run (Q3) - 2021-09-16

**Comment by softvision-oana-arbuzov** [comment]
[Done] 3rd run (Q3) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=603406939

UA Overrides to be removed:
[1731089](https://bugzilla.mozilla.org/show_bug.cgi?id=1731089) Remove UA Override for tieba.baidu.com
[1731254](https://bugzilla.mozilla.org/show_bug.cgi?id=1731254) Remove UA Override for avto.pro 
[1731268](https://bugzilla.mozilla.org/show_bug.cgi?id=1731268) Remove UA Override for spectrum.net/voice/

Interventions to be removed:
[1731071](https://bugzilla.mozilla.org/show_bug.cgi?id=1731071) Remove Intervention for Sites using PDK 5 video
[1731083](https://bugzilla.mozilla.org/show_bug.cgi?id=1731083) Remove Intervention for s-kanava.fi

**Comment by softvision-oana-arbuzov** [comment]
1st QA run (Q4) - 2021-10-14

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st run (Q4) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=347647518

**Comment by softvision-oana-arbuzov** [comment]
2nd QA run (Q4) - 2021-11-17

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2dn run (Q4) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=810301049

**Comment by softvision-oana-arbuzov** [comment]
3rd QA run (Q4) - 2021-12-20

**Comment by denschub** [comment]
Version 29 has been shipped - in time on Desktop, but with some delay on Mobile due to some issues. No big deal, it made it into a release anyway. :)

And with that, this goal is done, there are no more interventions to be released this year. Thanks to everyone who sometimes had more interventions to build because I sneakily assigned them some issues from the backlog, and thanks to @softvision-oana-arbuzov for always helping out with the verification. <3

**Comment by softvision-oana-arbuzov** [comment]
Thanks @denschub and thanks @softvision-raul-bucata for helping out with this task.

[Done] 3rd run (Q4) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1998440871

Interventions to be removed:
[1747366](https://bugzilla.mozilla.org/show_bug.cgi?id=1747366) Remove Intervention for lu.ma
[1747373](https://bugzilla.mozilla.org/show_bug.cgi?id=1747373) Remove Intervention for teamcoco.com

UA Overrides to be removed:
[1747389](https://bugzilla.mozilla.org/show_bug.cgi?id=1747389) Remove UA Override for goal.com

**Comment by denschub** [comment]
Completed OKR-tracking-issue, thou shalt be closed.
