### ISSUE TITLE
2022H1 - Site Intervension Release 

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#250]
Manual execution (issues related to 2fa/geo-location/code verification) and Automated Test Suite progress for Interventions and UA Overrides.

* [x] Version 30 for Firefox 98 (Soft Freeze: 2022-02-03) - @ksy36  - [Bugzilla Bug #1749436](https://bugzilla.mozilla.org/show_bug.cgi?id=1749436)
* [x] Version 31 for Firefox 99 (Soft Freeze: 2022-03-03) - @wisniewskit - [Bugzilla Bug #1752986](https://bugzilla.mozilla.org/show_bug.cgi?id=1752986)
* [x] Version 100 (Soft Freeze: 2022-03-31) - @denschub - [Bugzilla Bug #1752987](https://bugzilla.mozilla.org/show_bug.cgi?id=1752987)
* [x] Version 101 (Soft Freeze: 2022-04-28) - @denschub - [Bugzilla Bug #1752988](https://bugzilla.mozilla.org/show_bug.cgi?id=1752988)
* [x] Version 102 (Soft Freeze: 2022-05-26) - @ksy36 - [Bugzilla Bug #1752989](https://bugzilla.mozilla.org/show_bug.cgi?id=1752989)
* [x] Version 103 (Soft Freeze: 2022-06-23) - @denschub - [Bugzilla Bug #1752990](https://bugzilla.mozilla.org/show_bug.cgi?id=1752990)

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st Manual run (Q1) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=502946932

**Intervention to be removed:**
[1751220](https://bugzilla.mozilla.org/show_bug.cgi?id=1751220) Remove Intervention for air-quality.com

**Comment by softvision-oana-arbuzov** [comment]
Next run: 17.02.2022

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd Manual run (Q1) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1103212077

**UA Overrides to be removed:**
[1755893](https://bugzilla.mozilla.org/show_bug.cgi?id=1755893)  Remove UA Override for ebuyer.com

**Intervention to be removed:**
[1755941](https://bugzilla.mozilla.org/show_bug.cgi?id=1755941) Remove intervention for chanel.com
[1755948](https://bugzilla.mozilla.org/show_bug.cgi?id=1755948) Remove intervention for tesla.com
[1755955](https://bugzilla.mozilla.org/show_bug.cgi?id=1755955) Remove intervention for vuoriclothing.com
[1755953](https://bugzilla.mozilla.org/show_bug.cgi?id=1755953) Remove intervention for bonappetit.com

**Comment by softvision-oana-arbuzov** [comment]
Next run: 17.03.2022

**Comment by softvision-raul-bucata** [comment]
[Done] 3rd Manual run (Q1)-  QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1815160789

**UA Overrides to be removed:**
[1760149](https://bugzilla.mozilla.org/show_bug.cgi?id=1760149) Remove UA Override for [bracketchallenge.ncaa.com](http://bracketchallenge.ncaa.com/)

**Interventions to be removed:**
[1760043](https://bugzilla.mozilla.org/show_bug.cgi?id=1760043) Remove Intervention for [zillow.com](http://zillow.com/)

**Comment by softvision-oana-arbuzov** [comment]
I've also executed the Automation Test Suite and below are the results:

**First run:** 
Ran 38 checks (38 tests)
Expected results: 27

Skipped: 8 tests
SKIPPED bug #1570108 - login info required for  
SKIPPED bug #1577519 - Region-locked, cannot test. Try using a VPN set to USA for 
SKIPPED bug #1610344 - Region-locked, cannot test. Try using a VPN set to USA for 
SKIPPED bug #1644830 - login info required for 

Unexpected results: 3
  test: 3 (3 fail)
FAILED bug #1472075 bankofamerica.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar
FAILED bug #1582582_sling_com.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section
FAILED bug#1719859_saxoinvestor.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section

**2nd run:** 
PASSED VPN USA - bug #1577519
PASSED VPN USA - bug #1610344

**Comment by ksy36** [comment]
Update on Firefox v100 override: 

brownells.com is fixed (https://github.com/webcompat/web-bugs/issues/90806) 

I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1762465 to update Firefox v100 override for v101 version of the addon.

**Comment by softvision-oana-arbuzov** [comment]
Next run: 14.04.2022

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st Manual run (Q2)- QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=176668246

**UA Overrides to be removed:**
[1764734](https://bugzilla.mozilla.org/show_bug.cgi?id=1764734) Remove UA Override for [expertflyer.com](http://expertflyer.com/)

**Interventions to be removed:**
Intervention for [instagram.com](http://instagram.com/) can be removed based on [1763100](https://bugzilla.mozilla.org/show_bug.cgi?id=1763100)
Intervention for `Download prompt for files with no content-type` can be removed based on [1652025](https://bugzilla.mozilla.org/show_bug.cgi?id=1652025)
Intervention for `Office Excel spreadsheets` can be removed based on [1710754](https://bugzilla.mozilla.org/show_bug.cgi?id=1710754)

**Comment by softvision-oana-arbuzov** [comment]
I've also executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 39 checks (39 tests)
Expected results: 22

Skipped: 4 tests
SKIPPED bug #1570108 - login info required  
SKIPPED bug #1644830 - login info required 

Unexpected results: 13 (1 error, 12 fail)
FAILED bug #[1472075](https://bugzilla.mozilla.org/show_bug.cgi?id=1472075) - Message: Unable to locate element: #browserUpgradeNoticeBar
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1582582](https://bugzilla.mozilla.org/show_bug.cgi?id=1582582) Message: Unable to locate element: unsupported-platform
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1610344](https://bugzilla.mozilla.org/show_bug.cgi?id=1610344) - assert ((True and False) or (not True))
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1631811](https://bugzilla.mozilla.org/show_bug.cgi?id=1631811) - assert False
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1711082](https://bugzilla.mozilla.org/show_bug.cgi?id=1711082) - Message: Failed to decode response from marionette
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1712833](https://bugzilla.mozilla.org/show_bug.cgi?id=1712833) - Message: Tried to run command without establishing a connection
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1719846](https://bugzilla.mozilla.org/show_bug.cgi?id=1719846) - Message: Tried to run command without establishing a connection
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1719859](https://bugzilla.mozilla.org/show_bug.cgi?id=1719859) - Message: Tried to run command without establishing a connection
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug#[1719870](https://bugzilla.mozilla.org/show_bug.cgi?id=1719870) - Message: Unable to locate element: #content > div
session = <selenium.webdriver.remote.webdriver.WebDriver (session="1ec46826-2b2b-4a3f-81bb-2c6a62dc90c7")>
FAILED bug #[1738313](https://bugzilla.mozilla.org/show_bug.cgi?id=1738313) Message: Tried to run command without establishing a connection
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
FAILED bug #[1741234](https://bugzilla.mozilla.org/show_bug.cgi?id=1741234) Message: Tried to run command without establishing a connection
session = <selenium.webdriver.remote.webdriver.WebDriver (session="dcefb4e5-94e9-4713-9870-8cd2834e3fe1")>
ERROR bug #[1741234](https://bugzilla.mozilla.org/show_bug.cgi?id=1741234) - teardown error
tp = <class 'selenium.common.exceptions.InvalidSessionIdException'>

Log file: [logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/8505879/logfile.zip)

**Note:** 
- For [1570108](https://bugzilla.mozilla.org/show_bug.cgi?id=1570108) - the UA Override is still needed.
- For [1644830](https://bugzilla.mozilla.org/show_bug.cgi?id=1644830) - the Intervention is still needed.

**Second run (for Failed Tests):**
- 5 tests passed
PASSED bug #[1711082](https://bugzilla.mozilla.org/show_bug.cgi?id=1711082)
PASSED bug #[1712833](https://bugzilla.mozilla.org/show_bug.cgi?id=1712833)
PASSED bug #[1719846](https://bugzilla.mozilla.org/show_bug.cgi?id=1719846)
PASSED bug #[1738313](https://bugzilla.mozilla.org/show_bug.cgi?id=1738313)
PASSED bug #[1741234](https://bugzilla.mozilla.org/show_bug.cgi?id=1741234)

- 6 tests failed
FAILED bug #[1472075](https://bugzilla.mozilla.org/show_bug.cgi?id=1472075)
FAILED bug #[1582582](https://bugzilla.mozilla.org/show_bug.cgi?id=1582582)
FAILED bug #[1610344](https://bugzilla.mozilla.org/show_bug.cgi?id=1610344)
FAILED bug #[1631811](https://bugzilla.mozilla.org/show_bug.cgi?id=1631811)
FAILED bug #[1719859](https://bugzilla.mozilla.org/show_bug.cgi?id=1719859)
FAILED bug #[1719870](https://bugzilla.mozilla.org/show_bug.cgi?id=1719870)

**Comment by softvision-oana-arbuzov** [comment]
Next run: 12.05.2022

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd Manual run (Q2)- QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=438080433

**UA Overrides to be removed:**
[1769073](https://bugzilla.mozilla.org/show_bug.cgi?id=1769073) Remove UA Override for sites returning desktop site instead of mobile site for Android 12

**Interventions to be removed:**
[1769053](https://bugzilla.mozilla.org/show_bug.cgi?id=1769053) Remove Intervention for nexity.fr

**Comment by softvision-oana-arbuzov** [comment]
I've also executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 39 checks (39 tests)
Expected results: 20

Skipped: 4 tests
SKIPPED bug #1570108 - login info required
SKIPPED bug #1644830 - login info required

Unexpected results: 15
  test: 15 (1 error, 14 fail)
FAILED 1457335_histography.py::test_disabled[without_interventions]
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions]
FAILED 1631811_datastudio.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1712833_desuca.py::test_disabled[without_interventions]
FAILED 1719846_covid_cdc_gov.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
FAILED 1738313_curriculum_gov_bc_ca.py::test_disabled[without_interventions]
FAILED 1741234_alphalabs.py::test_disabled[without_interventions]
ERROR 1741234_alphalabs.py::test_disabled[without_interventions]

Log file: [AutomationRUn_logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/8707814/AutomationRUn_logfile.zip)

**Second run (for Failed Tests):**
- 8 tests failed
FAILED 1457335_histography.py: AssertionError: assert 'http://histography.io/' == 'http://histograp...wser_support.htm'
FAILED 1472075_bankofamerica.py: selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar
FAILED 1582582_sling_com.py:  selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: unsupported-platform
FAILED 1610344_directv_com_co.py: assert ((True and False) or (not True))
FAILED 1631811_datastudio.py: assert False
session = <selenium.webdriver.remote.webdriver.WebDriver (session="e0ac90ee-69cb-4c48-8728-4efca479ea2b")>
FAILED 1711082_aliexpress.py: selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1719859_saxoinvestor.py: selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section
FAILED 1719870_lcbo.py: selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div

- 4 tests passed
PASSED 1712833_desuca.py
PASSED 1719846_covid_cdc_gov.py
PASSED 1738313_curriculum_gov_bc_ca.py
PASSED 1741234_alphalabs.py

**Comment by denschub** [comment]
I'll take over 103, as Tom is still working on Privacy stuff. I hope I'll have some cycles to look into the failing tests mentioned in @softvision-oana-arbuzov's previous comment, and catch up on adding tests for current interventions.

**Comment by softvision-oana-arbuzov** [comment]
Next run: 09.06.2022

**Comment by softvision-oana-arbuzov** [comment]
[Done] 3rd Manual run (Q2)- QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=477077755

**Interventions to be removed:**
[1773445](https://bugzilla.mozilla.org/show_bug.cgi?id=1773445) Remove Intervention for m.aliexpress.com 
[1773522](https://bugzilla.mozilla.org/show_bug.cgi?id=1773522) Remove Intervention for zee5.com

**Comment by softvision-oana-arbuzov** [comment]
I've also executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 39 checks (39 tests)
Expected results: 21

Skipped: 4 tests
SKIPPED bug #1570108 - login info required
SKIPPED bug #1644830 - login info required

Unexpected results: 14
test: 14 (1 error, 13 fail)
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions]
FAILED 1631811_datastudio.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1712833_desuca.py::test_disabled[without_interventions]
FAILED 1719846_covid_cdc_gov.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
FAILED 1738313_curriculum_gov_bc_ca.py::test_disabled[without_interventions]
FAILED 1741234_alphalabs.py::test_disabled[without_interventions]
ERROR 1741234_alphalabs.py::test_disabled[without_interventions]

Log file: [AutomationRunTS_logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/8877438/AutomationRunTS_logfile.zip)

**Second run (for Failed Tests):**
- 8 tests failed
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar
FAILED 1582582_sling_com.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: unsupported-platform
FAILED 1631811_datastudio.py::test_disabled[without_interventions] - assert False
FAILED 1711082_aliexpress.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
 0:29.83 TEST_END: FAIL, expected PASS - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
 0:19.05 TEST_END: FAIL, expected PASS - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div
FAILED 1719870_lcbo.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div

- 5 tests passed
PASSED 1610344_directv_com_co.py
PASSED 1712833_desuca.py
PASSED 1719846_covid_cdc_gov.py
PASSED 1738313_curriculum_gov_bc_ca.p
PASSED 1741234_alphalabs.py

**Comment by softvision-oana-arbuzov** [comment]
This is complete.
