### ISSUE TITLE
Tracking Protection Issues and Webcompat infrastructure

### ISSUE THREAD

**Issue by karlcow** [mozilla/webcompat-team-okrs#255]
This issue here is to record understanding and state of discussions on what is happening around tracking protection issues and how the webcompat team can provide the knowledge for the privacy team to organize themselves. 

Some possible topics that needs to be addressed. 

* [ ] Triage expertise @softvision-oana-arbuzov @softvision-raul-bucata 
* [ ] webcompat.com infrastructure @ksy36 
* [ ] webcompat ML bot @ksy36 
* [ ] Management issues 
* [ ] Tracking protection issues diagnosis (someone in the privacy team)

## Discussions Leads on webcompat side

@ksy36 and @wisniewskit are the two leads for this discussion on the webcompat side. 

## Background

The Privacy team has a repo which collects ETP related issues. (private only)
https://github.com/mozilla/tracking-protection-issues-private/issues/

As of March 10, 2022

| Repo | Total issues  | Start date | issues/day |
| --- | --- | --- | --- |
| [Privacy issues](https://github.com/mozilla/tracking-protection-issues-private/issues/) | ~146,000  | July 2018  |  146 |
| [Webcompat issues](https://github.com/webcompat/web-bugs/issues) | ~100,000  | January 2016  | 99 | 

## Current Triage on webcompat side for ETP issues

Webcompat team sometimes receives ETP issues on [webcompat.com](http://webcompat.com/). Each time this is happening they are being tested and [transferred to bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1101005). If a triage process was created by the Privacy team we could imagine moving the bug which are in webcompat/web-bugs to mozilla/tracking-protection-issues-private

## Triage on Privacy side for webcompat issues

To the best of the webcompat team knowledge, the issues landing on [mozilla/tracking-protection-issues-private](https://github.com/mozilla/tracking-protection-issues-private/issues/) are not being triaged nor shared with the webcompat team. We can perfectly imagine a system, when someone reported wrongly webcompat issues on ETP infrastructure to have them moved to https://github.com/webcompat/web-bugs/issues .

## Some CAN and CAN NOT

* webcompat team can NOT absorb the volume of issues that tracking protection is receiving. The Privacy team would have to set up their own triage team and their own ML bot.
* webcompat team can provide expertise and formation on how to do the triage 
* webcompat team can provide expertise on how to tweak an ML bot for the mozilla/tracking-protection-issues-private repo.
