### ISSUE TITLE
2022H2 - Site Intervension Release

### ISSUE THREAD

**Issue by denschub** [mozilla/webcompat-team-okrs#258]
Manual execution (issues related to 2fa/geo-location/code verification) and Automated Test Suite progress for Interventions and UA Overrides - and building and shipping those!

- [x] Version 104 (Soft Freeze: 2022-07-21) - @wisniewskit - [#1776673](https://bugzilla.mozilla.org/show_bug.cgi?id=1776673)
- [x] Version 105 (Soft Freeze: 2022-08-18) - @ksy36 - [#1776674](https://bugzilla.mozilla.org/show_bug.cgi?id=1776674)
- [x] Version 106 (Soft Freeze: 2022-09-15) - @denschub - [#1776675](https://bugzilla.mozilla.org/show_bug.cgi?id=1776675)
- [x] Version 107 (Soft Freeze: 2022-10-13) - @denschub - [#1776676](https://bugzilla.mozilla.org/show_bug.cgi?id=1776676)
- [x] Version 108 (Soft Freeze: 2022-11-10) - @wisniewskit - [#1776677](https://bugzilla.mozilla.org/show_bug.cgi?id=1776677)
- [x] Version 109 (Soft Freeze: 2022-12-08) - @ksy36 - [#1776678](https://bugzilla.mozilla.org/show_bug.cgi?id=1776678)

**Comment by softvision-oana-arbuzov** [comment]
First QA run - 07.07.2022

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st Manual run (Q3) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=222766122

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st Automation run (Q3) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 39 checks (39 tests)
Expected results: 22

Skipped: 4 tests
SKIPPED bug #1570108 - login info required
SKIPPED bug #1644830 - login info required

Unexpected results: 13 (1 error, 12 fail)
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1631811_datastudio.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1712833_desuca.py::test_disabled[without_interventions]
FAILED 1719846_covid_cdc_gov.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
FAILED 1738313_curriculum_gov_bc_ca.py::test_disabled[without_interventions]
FAILED 1741234_alphalabs.py::test_disabled[without_interventions]
ERROR 1741234_alphalabs.py::test_disabled[without_interventions]

Log file: [AutomationRun_logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/9063202/AutomationRun_logfile.zip)

**Second run (for Failed Tests):**

- 8 tests failed
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar
FAILED 1582582_sling_com.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: unsupported-platform
FAILED 1631811_datastudio.py::test_disabled[without_interventions] - assert False
FAILED 1711082_aliexpress.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section
FAILED 1719870_lcbo.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div
FAILED 1719870_lcbo.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div

- 4 tests passed
PASSED 1712833_desuca.py
PASSED 1719846_covid_cdc_gov.py
PASSED 1738313_curriculum_gov_bc_ca.py
PASSED 1741234_alphalabs.py

Note: aliexpress.py test can be removed, the Intervention was removed, based on [1773445](https://bugzilla.mozilla.org/show_bug.cgi?id=1773445)

**Comment by softvision-oana-arbuzov** [comment]
2nd QA run - 04.08.2022

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd Automation run (Q3) 
I've executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 38 checks (38 tests)
Expected results: 26

Skipped: 4 tests
SKIPPED bug #1570108 - login info required
SKIPPED bug #1644830 - login info required

Unexpected results: 8 (8 fail)
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_enabled[with_interventions] 
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_enabled[with_interventions]

[Automation_logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/9257784/Automation_logfile.zip)

**Second run (for Failed Tests):**
- 8 tests failed
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar
FAILED 1582582_sling_com.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: unsupported-platform
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions] - assert ((True and False) or (not True))
FAILED 1711082_aliexpress.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section
FAILED 1719870_lcbo.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div
FAILED 1719870_lcbo.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar

**Comment by softvision-oana-arbuzov** [comment]
[Done] 2nd Manual run (Q3) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=43704876

**Comment by softvision-oana-arbuzov** [comment]
3rd QA run - 01.09.2022

**Comment by softvision-raul-bucata** [comment]
[Done] 3rd Manual run (Q3) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=43704876

**Comment by softvision-oana-arbuzov** [comment]
[Done] 3rd Manual run (Q3) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1907949384

Some issue are no longer reproducible regardless if the Intervention is enabled or not, but due to a crash in `about:compat` (`about:config`) https://github.com/mozilla-mobile/fenix/issues/26759 , we'll keep them and verify them when the crash is fixed.
[1551672](https://bugzilla.mozilla.org/show_bug.cgi?id=1551672) Sites using PDK 5 video
[1610358](https://bugzilla.mozilla.org/show_bug.cgi?id=1610358) [pcloud.com](http://pcloud.com/)

**Comment by softvision-oana-arbuzov** [comment]
[Done] 3rd Automation run (Q3)
I've executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 39 checks (39 tests)
Expected results: 21

Skipped: 4 tests
SKIPPED bug #1570108 - login info required
SKIPPED bug #1644830 - login info required

Unexpected results: 14 (1 error 13 fail)
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions]
FAILED 1631811_datastudio.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1712833_desuca.py::test_disabled[without_interventions]
FAILED 1719846_covid_cdc_gov.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
FAILED 1738313_curriculum_gov_bc_ca.py::test_disabled[without_interventions]
FAILED 1741234_alphalabs.py::test_disabled[without_interventions]
ERROR 1741234_alphalabs.py::test_disabled[without_interventions]

Automation log: [logfileAutomation.zip](https://github.com/mozilla/webcompat-team-okrs/files/9477848/logfileAutomation.zip)

**Second run (for Failed Tests):**

- 8 tests failed
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar
FAILED 1582582_sling_com.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: unsupported-platform
FAILED 1631811_datastudio.py::test_disabled[without_interventions] - assert False
FAILED 1711082_aliexpress.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section
FAILED 1719870_lcbo.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div
FAILED 1719870_lcbo.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar

- 5 passed
PASSED 1610344_directv_com_co.py
PASSED 1712833_desuca.py
PASSED 1719846_covid_cdc_gov.py
PASSED 1738313_curriculum_gov_bc_ca.py
PASSED 1741234_alphalabs.py

**Comment by softvision-raul-bucata** [comment]
First Run (Q4) - 04.10.2022

**Comment by softvision-oana-arbuzov** [comment]
[Done] 1st Automation run (Q4)

I've executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 38 checks (38 tests)
Expected results: 26

Skipped: 4 tests
SKIPPED bug #1570108 - login info required
SKIPPED bug #1644830 - login info required

Unexpected results: 8 (8 fail)
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_enabled[with_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_enabled[with_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]

Log file: [Automation_logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/9703991/Automation_logfile.zip)

**Second run (for Failed Tests):**
- 7 tests failed
FAILED 1472075_bankofamerica.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar
FAILED 1582582_sling_com.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: unsupported-platform
FAILED 1711082_aliexpress.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #header input[placeholder]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browser_support_section
FAILED 1719870_lcbo.py::test_enabled[with_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #content > div
FAILED 1719870_lcbo.py::test_disabled[without_interventions] - selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #browserUpgradeNoticeBar

- 1 test passed
PASSED 1610344_directv_com_co.py

**Comment by softvision-raul-bucata** [comment]
[Done] 1st Manual Run (Q4) - QA Verification progress available here:
https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1164200933


**Interventions to be removed:**

[1652025](https://bugzilla.mozilla.org/show_bug.cgi?id=1652025) Remove Intervention for "Download prompt for files with no content-type"
[1793601](https://bugzilla.mozilla.org/show_bug.cgi?id=1793601) Remove Intervention for seznam.cz on mobile
[1790390](https://bugzilla.mozilla.org/show_bug.cgi?id=1790390) Remove interventions for pcloud.com

**Comment by softvision-raul-bucata** [comment]
Second run (Q4) - 27.10.2022.

**Comment by softvision-raul-bucata** [comment]
[Done] 2nd Atuomationl Run (Q4) - 
I've executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 38 checks (38 tests)
Expected results: 23

Skipped: 4 tests
SKIPPED login info required for bug #1570108
SKIPPED login info required for bug #1644830

Unexpected results: 11 (11 fail)

FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
FAILED 1738313_curriculum_gov_bc_ca.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_enabled[with_interventions]
FAILED 1666771_zillow.py::test_enabled[with_interventions]
FAILED 1711082_aliexpress.py::test_enabled[with_interventions]
FAILED 1719870_lcbo.py::test_enabled[with_interventions]

Log file:  [AutomationLog2ndRunQ4.zip](https://github.com/mozilla/webcompat-team-okrs/files/9879486/AutomationLog2ndRunQ4.zip)


**Second run (for Failed Tests):**
- 11 tests failed



- 3 tests passed
PASSED 1610344_directv_com_co.py 
PASSED  1666771_zillow.py
PASSED 1719870_lcbo.py

**Comment by softvision-raul-bucata** [comment]
[Done] 2nd Manual Run (Q4) - QA Verification progress available here:
https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=304532596

**Comment by softvision-raul-bucata** [comment]
3rd Run (Q4) - 24.11.2022

**Comment by softvision-raul-bucata** [comment]
[Done] 3rd Manual Run (Q4) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1164200933

**Interventions to be removed:**

[1802326](https://bugzilla.mozilla.org/show_bug.cgi?id=1802326)  Remove Intervention for Nintendo domains
[1802328](https://bugzilla.mozilla.org/show_bug.cgi?id=1802328)  Remove Intervention for microsoftedgetips.microsoft.com
[1802329](https://bugzilla.mozilla.org/show_bug.cgi?id=1802329)  Remove Intervention for nha.chotot.com
[1802339](https://bugzilla.mozilla.org/show_bug.cgi?id=1802339) Remove Intervention for Set navigator.share to undefined on YouTube iframe - femiwiki.com

**Comment by softvision-raul-bucata** [comment]
[Done] 3rd Atuomationl Run (Q4) - 
I've executed the Automation Test Suite and below are the results (VPN active pointing to USA):

**First run:**
Ran 38 checks (38 tests)
Expected results: 23

Skipped: 4 tests
SKIPPED login info required for bug #1570108
SKIPPED login info required for bug #1644830

Unexpected results: 11 (11 fail)

FAILED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1582582_sling_com.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_disabled[without_interventions]
FAILED 1711082_aliexpress.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1719870_lcbo.py::test_disabled[without_interventions]
FAILED 1738313_curriculum_gov_bc_ca.py::test_disabled[without_interventions]
FAILED 1610344_directv_com_co.py::test_enabled[with_interventions]
FAILED 1666771_zillow.py::test_enabled[with_interventions]
FAILED 1711082_aliexpress.py::test_enabled[with_interventions]
FAILED 1719870_lcbo.py::test_enabled[with_interventions]

Log file:  [logfile24nov.zip](https://github.com/mozilla/webcompat-team-okrs/files/10085977/logfile24nov.zip)


**Second run (for Failed Tests):**
- 10 tests failed

- 1 test passed: 1472075_bankofamerica

**Comment by denschub** [comment]
Aaaaaaaand it's done.
