### ISSUE TITLE
2023H1 - Site Intervension Release

### ISSUE THREAD

**Issue by denschub** [mozilla/webcompat-team-okrs#266]
- [x] Version 110 (Soft Freeze: 2023-01-12) - @denschub - [#1805407](https://bugzilla.mozilla.org/show_bug.cgi?id=1805407)
- [x] Version 111 (Soft Freeze: 2023-02-09) - @wisniewskit - [#1805408](https://bugzilla.mozilla.org/show_bug.cgi?id=1805408)
- [x] Version 112 (Soft Freeze: 2023-03-09) - @ksy36 - [#1805409](https://bugzilla.mozilla.org/show_bug.cgi?id=1805409)
- [x] Version 113 (Soft Freeze: 2023-04-06) - @denschub - [#1805410](https://bugzilla.mozilla.org/show_bug.cgi?id=1805410)
- [x] Version 114 (Soft Freeze: 2023-05-04) - @wisniewskit - [#1805411](https://bugzilla.mozilla.org/show_bug.cgi?id=1805411)
- [x] Version 115 (Soft Freeze: 2023-06-01) - @ksy36 - [#1805412](https://bugzilla.mozilla.org/show_bug.cgi?id=1805412)

Let's try to keep up with automated tests this year! :)

**Comment by softvision-raul-bucata** [comment]
First run QA: 29.12.2022

**Comment by softvision-raul-bucata** [comment]
**[Done]** 1st Manual run (Q1 -2023) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=304532596

**Comment by softvision-raul-bucata** [comment]
**[Done]** 1st Automation run (Q1- 2023) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

**First run:**
Ran 52 checks (52 tests)
Expected results: 36
Skipped: 7 tests
FAILED: 9 tests


**Unexpected results:** 9 ( 9 fail)
FAILED 1582582_sling_com.py::test_enabled[with_interventions]
FAILED 1784199_entrata_platform.py::test_enabled[with_interventions]
FAILED 1786404_business_help_royalmail_com.py::test_enabled[with_interventions]
FAILED 1800241_mms_telekom_de.py::test_enabled[with_interventions]
FAILED 1800936_cov19ent_kdca_go_kr.py::test_enabled[with_interventions]
FAILED 1803976_youtube_com.py::test_enabled[with_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1800936_cov19ent_kdca_go_kr.py::test_disabled[without_interventions]



**Log file:** [logfile29dec.zip](https://github.com/mozilla/webcompat-team-okrs/files/10319194/logfile29dec.zip)

**Second run (for Failed Tests):**

Failed: 9 Tests

**Comment by softvision-raul-bucata** [comment]
Second Run QA: 26.01.2023

**Comment by softvision-raul-bucata** [comment]
**[Done]** 2ndManual run (Q1 -2023) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1b1K-Zk35uLCk_6n2I-aON-4yc0bkZWQQPme1Em59QOQ/edit#gid=1052084696

**Items to be removed:**

[1812583](https://bugzilla.mozilla.org/show_bug.cgi?id=1812583) Remove intervention for tiktok.com
[1812586](https://bugzilla.mozilla.org/show_bug.cgi?id=1812586) Remove intervention for movistar.com.ar
[1812588](https://bugzilla.mozilla.org/show_bug.cgi?id=1812588) Remove intervention for nutmeg.morrisons.com
[1812585](https://bugzilla.mozilla.org/show_bug.cgi?id=1812585) Remove UA Overrides/Interventions for nordjyske.dk

**Comment by softvision-raul-bucata** [comment]
**[Done]** 2nd Automation run (Q1- 2023) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

**First run:**
Ran 52 checks (52 tests)
Expected results: 35
Skipped: 7 tests
Failed: 10 tests


**Unexpected results:** 10( 10 fail)
FAILED 1582582_sling_com.py::test_enabled[with_interventions]
FAILED 1650317_livescience_com.py::test_enabled[with_interventions]
FAILED 1784199_entrata_platform.py::test_enabled[with_interventions]
FAILED 1786404_business_help_royalmail_com.py::test_enabled[with_interventions]
FAILED 1800241_mms_telekom_de.py::test_enabled[with_interventions]
FAILED 1800936_cov19ent_kdca_go_kr.py::test_enabled[with_interventions]
FAILED 1803976_youtube_com.py::test_enabled[with_interventions]
FAILED 1719846_covid_cdc_gov.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1786404_business_help_royalmail_com.py::test_disabled[without_interventions]

**Comment by softvision-raul-bucata** [comment]
Third Run QA: 23.02.2023

**Comment by softvision-raul-bucata** [comment]
**[Done]** 3rd Manual run (Q1 -2023) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1b1K-Zk35uLCk_6n2I-aON-4yc0bkZWQQPme1Em59QOQ/edit#gid=1737127724

**Items to be removed:**

[1818217](https://bugzilla.mozilla.org/show_bug.cgi?id=1818217) Remove UA Overrides/Interventions for m.pji.co.kr
[1818218](https://bugzilla.mozilla.org/show_bug.cgi?id=1818218) Remove UA Overrides/Interventions for burgerking.es
[1818220](https://bugzilla.mozilla.org/show_bug.cgi?id=1818220) Remove UA Overrides/Interventions for m.intl.taobao.com

**Comment by softvision-raul-bucata** [comment]
**[Done]** 3rd Automation run (Q1- 2023) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

**First run:**
Ran 52 checks (52 tests)
Expected results: 36
Skipped: 9 tests
Unexpected results: 7 (FAILED)




**Unexpected results:** 7( 7 fail)
FAILED 1577519_stream_directv_com.py::test_enabled[with_interventions]
FAILED 1631811_datastudio.py::test_enabled[with_interventions]
FAILED 1786404_business_help_royalmail_com.py::test_enabled[with_interventions] 
FAILED 1719846_covid_cdc_gov.py::test_disabled[without_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
FAILED 1778239_m_pji_co_kr.py::test_disabled[without_interventions]
FAILED 1786404_business_help_royalmail_com.py::test_disabled[without_interventions] 

**Log file:**
[23feb2023logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/10806708/23feb2023logfile.zip)


**2nd Automation run for failed tests:**
FAILED 1577519_stream_directv_com.py::test_enabled[with_interventions] Ran 2 checks (1 Pass/1 Fail)
FAILED 1631811_datastudio.py::test_enabled[with_interventions] Ran 2 checks (1Pass/1Fail)
FAILED 1786404_business_help_royalmail_com.py::test_enabled[with_interventions] Ran 2 checks (0 Pass/2 Fail)
FAILED 1719846_covid_cdc_gov.py::test_disabled[without_interventions] Ran 2 checks (1 Pass/1 Fail)
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions] Ran 2 checks (1 Pass/1 Fail)
FAILED 1778239_m_pji_co_kr.py::test_disabled[without_interventions] Ran 2 checks (1 Pass/1 Fail)
FAILED 1786404_business_help_royalmail_com.py::test_disabled[without_interventions] Ran 2 checks (0 Pass/2 Fail)

**Comment by softvision-raul-bucata** [comment]
Fourth Run QA: 23.03.2023

**Comment by softvision-raul-bucata** [comment]
**[Done]** 4th Manual run (Q1 -2023) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1b1K-Zk35uLCk_6n2I-aON-4yc0bkZWQQPme1Em59QOQ/edit#gid=1777081785

**Items to be removed:**

[1824164](https://bugzilla.mozilla.org/show_bug.cgi?id=1824164) Remove UA Overrides/Interventions for automesseweb.jp
[1824167](https://bugzilla.mozilla.org/show_bug.cgi?id=1824167) Remove Intervention for almosafer.com

**Comment by softvision-raul-bucata** [comment]
**[Done]** 4th Automation run (Q1- 2023) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

**First run:**
Ran 57 checks (57 tests)
Expected results: 44
Skipped: 7 tests
Unexpected results: 6 (1 error, 5 FAILED)




**Unexpected results:** 6( 1 error 5 fail)
FAILED 1631811_datastudio.py::test_enabled[with_interventions]
FAILED 1811325_inmac_wstore_com.py::test_enabled[with_interventions]
FAILED 1817520_ersthelfer_tv.py::test_enabled[with_interventions]
FAILED 1819476_axis_bank.py::test_enabled[with_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]
1 Error 500


**Log file:**
[23march2023logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/11052889/23march2023logfile.zip)



**2nd Automation run for failed tests:**
FAILED 1631811_datastudio.py::test_enabled[with_interventions]
FAILED 1811325_inmac_wstore_com.py::test_enabled[with_interventions]
FAILED 1817520_ersthelfer_tv.py::test_enabled[with_interventions]
FAILED 1819476_axis_bank.py::test_enabled[with_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]

**2nd Automation run for skipped tests:**
FAILED 1472075_bankofamerica.py::test_enabled[with_interventions]
PASSED 1644830_missingmail_usps.py::test_enabled[with_interventions]
FAILED 1570108_steamcommunity.py::test_enabled[with_interventions]
PASSED 1472075_bankofamerica.py::test_disabled[without_interventions]
FAILED 1570108_steamcommunity.py::test_disabled[without_interventions]
PASSED 1644830_missingmail_usps.py::test_disabled[without_interventions]
SKIPPED: 1803976_youtube_com.py::test_disabled[without_interventions]

**Comment by softvision-raul-bucata** [comment]
Next Run QA: 20.04.2023

**Comment by softvision-raul-bucata** [comment]
**[Done]** 5th Manual run (Q2 -2023) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1b1K-Zk35uLCk_6n2I-aON-4yc0bkZWQQPme1Em59QOQ/edit#gid=2035890881

**Items to be removed:**

[1829150](https://bugzilla.mozilla.org/show_bug.cgi?id=1829150) Remove Intervention for reddit.com
[1829150](https://bugzilla.mozilla.org/show_bug.cgi?id=1829150) Remove Intervention for dns-shop.ru

**Comment by softvision-raul-bucata** [comment]
**[Done]** 5th Automation run (Q2- 2023) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

**First run:**
Ran 56 checks (56 tests)
Expected results: 42
Skipped: 7 tests
Unexpected results: 7
  test: 7 (7 fail)




**Unexpected results:** 7( 7 error 5 fail)
FAILED 1577519_stream_directv_com.py::test_enabled[with_interventions]
FAILED 1631811_datastudio.py::test_enabled[with_interventions]
FAILED 1800936_cov19ent_kdca_go_kr.py::test_enabled[with_interventions]
FAILED 1811325_inmac_wstore_com.py::test_enabled[with_interventions]
FAILED 1817520_ersthelfer_tv.py::test_enabled[with_interventions]
FAILED 1819476_axis_bank.py::test_enabled[with_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]


**Log file:**
[logfile20april2023.zip](https://github.com/mozilla/webcompat-team-okrs/files/11287343/logfile20april2023.zip)




**2nd Automation run for failed tests:**

PASS 1577519_stream_directv_com.py::test_enabled[with_interventions]
FAILED 1631811_datastudio.py::test_enabled[with_interventions]
PASS 1800936_cov19ent_kdca_go_kr.py::test_enabled[with_interventions]
FAILED 1811325_inmac_wstore_com.py::test_enabled[with_interventions]
FAILED 1817520_ersthelfer_tv.py::test_enabled[with_interventions]
FAILED 1819476_axis_bank.py::test_enabled[with_interventions]
FAILED 1719859_saxoinvestor.py::test_disabled[without_interventions]

**Comment by softvision-raul-bucata** [comment]
Next Run QA: 18.05.2023

**Comment by softvision-raul-bucata** [comment]
**[Done]** 6th Manual run (Q2 -2023) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1b1K-Zk35uLCk_6n2I-aON-4yc0bkZWQQPme1Em59QOQ/edit#gid=253915838

**Items to be removed:**

[1833868](https://bugzilla.mozilla.org/show_bug.cgi?id=1833868) Remove Intervention for covid.cdc.gov 
[1833865](https://bugzilla.mozilla.org/show_bug.cgi?id=1833865) Remove UA Overrides/Interventions for amextravel.com
[1833867](https://bugzilla.mozilla.org/show_bug.cgi?id=1833867) Remove UA Overrides/Interventions for eventer.co.il
[1833871](https://bugzilla.mozilla.org/show_bug.cgi?id=1833871) Remove UA Overrides/Interventions for youtube.com
[1833872](https://bugzilla.mozilla.org/show_bug.cgi?id=1833872) Remove UA Overrides/Interventions for elal.com

**Comment by softvision-raul-bucata** [comment]
**[Done]** 6th Automation run (Q2- 2023) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

**First run:**
Ran 93 checks (93 tests)
Expected results: 30
Skipped: 53 tests
Unexpected results: 10
test: 10 (10 fail)



**Unexpected results:** 10( 10 fails)
FAILED tests/test_1631811_datastudio.py::test_enabled[with_interventions]
FAILED tests/test_1719846_covid_cdc_gov.py::test_enabled[with_interventions]
FAILED tests/test_1784199_avanabayview_com.py::test_enabled[with_interventions]
FAILED tests/test_1784199_breakpointeandcoronado_com.py::test_enabled[with_interventions]
FAILED tests/test_1784199_midwayurban_com.py::test_enabled[with_interventions]
FAILED tests/test_1784199_vanallenapartments_com.py::test_enabled[with_interventions] 
FAILED tests/test_1811325_inmac_wstore_com.py::test_enabled[with_interventions]
FAILED tests/test_1817520_ersthelfer_tv.py::test_enabled[with_interventions]
FAILED tests/test_1819476_axis_bank.py::test_enabled[with_interventions]
FAILED tests/test_1819476_axisbank_com.py::test_enabled[with_interventions]


**Log file:**



[18may2023logfile.zip](https://github.com/mozilla/webcompat-team-okrs/files/11508419/18may2023logfile.zip)


**2nd Automation run for failed tests:**

FAILED tests/test_1631811_datastudio.py::test_enabled[with_interventions]
FAILED tests/test_1719846_covid_cdc_gov.py::test_enabled[with_interventions]
FAILED tests/test_1784199_avanabayview_com.py::test_enabled[with_interventions]
FAILED tests/test_1784199_breakpointeandcoronado_com.py::test_enabled[with_interventions]
FAILED tests/test_1784199_midwayurban_com.py::test_enabled[with_interventions]
FAILED tests/test_1784199_vanallenapartments_com.py::test_enabled[with_interventions] 
FAILED tests/test_1811325_inmac_wstore_com.py::test_enabled[with_interventions]
FAILED tests/test_1817520_ersthelfer_tv.py::test_enabled[with_interventions]
FAILED tests/test_1819476_axis_bank.py::test_enabled[with_interventions]
FAILED tests/test_1819476_axisbank_com.py::test_enabled[with_interventions]

**Comment by softvision-raul-bucata** [comment]
This was the run for H1 2023, completed.
