### ISSUE TITLE
2024H1 - Site Intervension Release

### ISSUE THREAD

**Issue by ksy36** [mozilla/webcompat-team-okrs#281]
Release calendar: https://whattrainisitnow.com/calendar/

- [x] Version 124 (Soft freeze 2024-02-15) - @wisniewskit  - [#1876360](https://bugzilla.mozilla.org/show_bug.cgi?id=1876360)
- [x] Version 125 (Soft freeze 2024-03-14) - @ksy36 - [#1876363](https://bugzilla.mozilla.org/show_bug.cgi?id=1876363)
- [x] Version 126 (Soft freeze 2024-04-11) - @denschub  - [#1876364](https://bugzilla.mozilla.org/show_bug.cgi?id=1876364)
- [x] Version 127 (Soft freeze 2024-05-09) - @wisniewskit  - [#1876367](https://bugzilla.mozilla.org/show_bug.cgi?id=1876367)
- [x] Version 128 (Soft freeze 2024-06-06) - @ksy36 -[#1876368](https://bugzilla.mozilla.org/show_bug.cgi?id=1876368)

**Comment by softvision-raul-bucata** [comment]
[Done] 1st Manual run (H1 -2024) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1PxBjSmGB5qysegCu39eevAS1PArYolL5hQyqzBo2VY0/edit#gid=1123249785

Items to be removed:

* [1877999](https://bugzilla.mozilla.org/show_bug.cgi?id=1877999) Remove intervention for datastudio.google.com
* [1878004](https://bugzilla.mozilla.org/show_bug.cgi?id=1878004) Remove intervention for preev.com
* [1878007](https://bugzilla.mozilla.org/show_bug.cgi?id=1878007) Remove intervention for elal.com
* [1877980](https://bugzilla.mozilla.org/show_bug.cgi?id=1877980) Remove Interventions for cov19ent.kdca.go.kr
* [1877986](https://bugzilla.mozilla.org/show_bug.cgi?id=1877986) Remove Interventions for sistema.ibglbrasil.com.br
* [1877991](https://bugzilla.mozilla.org/show_bug.cgi?id=1877991) Remove Interventions for f2bbs.com
* [1877993](https://bugzilla.mozilla.org/show_bug.cgi?id=1877993) Remove Interventions for otsuka.co.jp (Mobile re-ship)

**Comment by softvision-raul-bucata** [comment]
**[Done]** 1st Automation run (H1- 2024) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

`Desktop`

**First run:**

Ran 119 checks (119 tests)
Expected results: 44
Skipped: 69 tests
Unexpected results: 6
  test: 6 (6 fail)



**Unexpected results:** 6( 6 fails)

FAIL tests/test_1650317_livescience_com.py::test_enabled[with_interventions] - asyncio.exceptions.CancelledError
FAIL tests/test_1741234_alphalabs.py::test_enabled[with_interventions] - webdriver.bidi.error.UnknownErrorException: unknown error (Error: NS_ERROR_NET_TIMEOUT)
FAIL tests/test_1784199_liveatlasathens_com.py::test_enabled[with_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1800936_cov19ent_kdca_go_kr.py::test_enabled[with_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1819476_axisbank_com.py::test_enabled[with_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1830813_onstove_com.py::test_enabled[with_interventions] - assert 0 == 120


**Log file:**

[January2024t4Desktop.txt](https://github.com/mozilla/webcompat-team-okrs/files/14126837/January2024t4Desktop.txt)



`Android`

**First run:**
Ran 237 checks (237 tests)
Expected results: 0
Unexpected results: 237
 test: 237 (237 error)
  







**Log file:**
[January2024Android.txt](https://github.com/mozilla/webcompat-team-okrs/files/14126784/January2024Android.txt)

**Comment by softvision-raul-bucata** [comment]
[Done] 2nd Manual run (H1 -2024) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1PxBjSmGB5qysegCu39eevAS1PArYolL5hQyqzBo2VY0/edit#gid=1123249785

Items to be removed:

* [1882784](https://bugzilla.mozilla.org/show_bug.cgi?id=1882784) Remove intervention for uniqlo mobile sites
* [1882788](https://bugzilla.mozilla.org/show_bug.cgi?id=1882788) Remove intervention for wolf777.com

**Comment by softvision-raul-bucata** [comment]
**[Done]** 2nd Automation run (H1- 2024) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

`Desktop`

**First run:**
Can not complete run due to `1709125846609   addons.xpi      ERROR   System addon update list error SyntaxError: XMLHttpRequest.open: 'http://%(server)s/dummy-system-addons.xml' is not a valid URL.` error






**Log file:**

N/A



`Android`

**First run:**
Ran 119 checks (119 tests)
Expected results: 78
Skipped: 20 tests
Unexpected results: 21
  test: 21 (21 fail)







**Log file:**

[February2024Android.txt](https://github.com/mozilla/webcompat-team-okrs/files/14450158/February2024Android.txt)

**Comment by softvision-raul-bucata** [comment]
Next Run: 28.03.2024

**Comment by softvision-raul-bucata** [comment]
[Done] 3rd Manual run (H1 -2024) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1PxBjSmGB5qysegCu39eevAS1PArYolL5hQyqzBo2VY0/edit#gid=1123249785

Items to be removed:

* [1888402](https://bugzilla.mozilla.org/show_bug.cgi?id=1888402) Remove intervention for teletrader.com
* [1888392](https://bugzilla.mozilla.org/show_bug.cgi?id=1888392) Remove Interventions for carefirst.com
* [1888395](https://bugzilla.mozilla.org/show_bug.cgi?id=1888395) Remove Interventions for enuri.com
* [1888397](https://bugzilla.mozilla.org/show_bug.cgi?id=1888397) Remove Interventions for ceskatelevize.cz
* [1888399](https://bugzilla.mozilla.org/show_bug.cgi?id=1888399) Remove Interventions for app.xiaomi.com
* [1888401](https://bugzilla.mozilla.org/show_bug.cgi?id=1888401) Remove Interventions for saxoinvestor.fr
* [1888405](https://bugzilla.mozilla.org/show_bug.cgi?id=1888405) Remove Interventions for vmos.cn
* [1888408](https://bugzilla.mozilla.org/show_bug.cgi?id=1888408) Remove Interventions for webcartop.jp
* [1888409](https://bugzilla.mozilla.org/show_bug.cgi?id=1888409) Remove Interventions for forum.memurlar.net

**Comment by softvision-raul-bucata** [comment]
**[Done]** 3rd Automation run (H1- 2024) 
I've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

`Desktop`


**First run:**

Ran 237 checks (237 tests)
Expected results: 90
Skipped: 135 tests(android tests)
Unexpected results: 12
  test: 12 (12 fail)

**Unexpected results:** 12( 12 fails)
FAIL tests/test_1650317_livescience_com.py::test_enabled[with_interventions] - asyncio.exceptions.CancelledError
FAIL tests/test_1784199_liveatlasathens_com.py::test_enabled[with_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1800936_cov19ent_kdca_go_kr.py::test_enabled[with_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1819476_axisbank_com.py::test_enabled[with_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1830813_onstove_com.py::test_enabled[with_interventions] - assert 0 == 120
FAIL tests/test_1848716_elal_com.py::test_enabled[with_interventions] - assert not True
FAIL tests/test_1631811_datastudio.py::test_disabled[without_interventions] - assert False
FAIL tests/test_1650317_livescience_com.py::test_disabled[without_interventions] - asyncio.exceptions.CancelledError
FAIL tests/test_1784199_liveatlasathens_com.py::test_disabled[without_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1800000_www_honda_co_uk.py::test_disabled[without_interventions] - assert not True
FAIL tests/test_1800936_cov19ent_kdca_go_kr.py::test_disabled[without_interventions] - webdriver.error.NoSuchElementException: no such element (404)
FAIL tests/test_1849018_carefirst_com.py::test_disabled[without_interventions] - webdriver.error.NoSuchElementException: no such element (404)






**Log file:**


[marchRun2024Desktop.txt](https://github.com/mozilla/webcompat-team-okrs/files/14792325/marchRun2024Desktop.txt)



`Android`
N/A

**Comment by softvision-raul-bucata** [comment]
Next Run: 25.04.2024

**Comment by softvision-raul-bucata** [comment]
[Done] 4th Manual run (H1 -2024) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1PxBjSmGB5qysegCu39eevAS1PArYolL5hQyqzBo2VY0/edit#gid=1123249785

**Comment by softvision-raul-bucata** [comment]
**[Done]** 4th Automation run (H1- 2024) 
We've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

`Desktop`


**First run:**

Ran 237 checks (237 tests)
Expected results: 87
Skipped: 135 tests
Unexpected results: 15
  test: 15 (15 fail)


**Log file:**

[AprilRun2024Desktop.txt](https://github.com/mozilla/webcompat-team-okrs/files/15112700/AprilRun2023Desktop.txt)





`Android`



**First run:**

Ran 237 checks (237 tests)
Expected results: 148
Skipped: 35 tests
Unexpected results: 54
  test: 54 (54 fail)

**Log file:**
[April2024Android.txt](https://github.com/mozilla/webcompat-team-okrs/files/15112682/April2024Androidd.txt)

**Comment by softvision-raul-bucata** [comment]
Next run - 23.05.2024

**Comment by softvision-raul-bucata** [comment]
[Done] 5th Manual run (H1 -2024) - QA Verification progress available here: https://docs.google.com/spreadsheets/d/1PxBjSmGB5qysegCu39eevAS1PArYolL5hQyqzBo2VY0/edit#gid=1123249785

Items to be removed:


* [1448747](https://bugzilla.mozilla.org/show_bug.cgi?id=1448747) FastClick breakage
* [1849019](https://bugzilla.mozilla.org/show_bug.cgi?id=1849019) axa-assistance.pl
* [1868345](https://bugzilla.mozilla.org/show_bug.cgi?id=1868345) tvmovie.de
* [1836116](https://bugzilla.mozilla.org/show_bug.cgi?id=1836116) slushy.com
* [1836182](https://bugzilla.mozilla.org/show_bug.cgi?id=1836182) flatsatshadowglen.com
* [1819702](https://bugzilla.mozilla.org/show_bug.cgi?id=1819702) feelgoodcontacts.com

**Comment by softvision-raul-bucata** [comment]
**[Done]** 5th Automation run (H1- 2024) 
We've also executed the Automation Test Suite and below are the results (VPN active pointing to the USA):

`Desktop`


**First run:**
Ran 119 checks (119 tests)
Expected results: 43
Skipped: 69 tests
Unexpected results: 7
  test: 7 (7 fail)
 
**Second run:**
Ran 237 checks (237 tests)
Expected results: 84
Skipped: 137 tests
Unexpected results: 16
  test: 16 (16 fail)


**Log file:**


[MayRun2024Desktop.txt](https://github.com/mozilla/webcompat-team-okrs/files/15418892/MayRun2024Desktop.txt)





`Android`
Can't test

**Comment by softvision-raul-bucata** [comment]
Next run - 20.06.2024
