### ISSUE TITLE
2019Q3 - 2.2 Ship 25 interventions for important sites (with focus on Fenix and EU)

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#89]
* Prioritize and ship interventions in Fenix (desktop counts here too)
* Focus on EU websites to support Android browser selection in EU.

**Comment by miketaylr** [comment]
List of candidates to choose from: https://github.com/webcompat/web-bugs/labels/type-uaoverride

**Comment by miketaylr** [comment]
* [x] https://github.com/webcompat/web-bugs/issues/17870
* [x] https://github.com/webcompat/web-bugs/issues/13154

**Comment by ksy36** [comment]
For the first patch thinking to do these UA overrides:

- [ ] https://github.com/webcompat/web-bugs/issues/25844

- [x] https://github.com/webcompat/web-bugs/issues/16648

- [ ] https://github.com/webcompat/web-bugs/issues/34171

And an intervention:

- [x] https://github.com/webcompat/web-bugs/issues/9102

**Comment by ksy36** [comment]
For webcompat/web-bugs#13154 there is an override already in place for Fennec, so we'll get it in Fenix with https://github.com/mozilla/webcompat-team-okrs/issues/88

**Comment by adamopenweb** [comment]
Another site we should consider doing an 

- [ ] override: https://github.com/webcompat/web-bugs/issues/15276

**Comment by miketaylr** [comment]
(Updating the title here, we'll take Desktop interventions too)

**Comment by miketaylr** [comment]
https://github.com/webcompat/web-bugs/issues/23867 is a good candidate for both desktop and mobile.
(the override does not provide good user experience)

**Comment by miketaylr** [comment]
- [x] https://github.com/webcompat/web-bugs/issues/22494 is another desktop + mobile intervention.

**Comment by miketaylr** [comment]
* [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/35608

**Comment by miketaylr** [comment]
Update: in progress, having trouble testing locally. Possibly something is busted on Android?

**Comment by miketaylr** [comment]
* [ ] desktop candidate https://bugzilla.mozilla.org/show_bug.cgi?id=1560071

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/36277

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/4070

**Comment by miketaylr** [comment]
mobile candidate https://github.com/webcompat/web-bugs/issues/10113
(fixed now)

**Comment by miketaylr** [comment]
* [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/4201

**Comment by miketaylr** [comment]
mobile candidate https://github.com/webcompat/web-bugs/issues/3961
(the patch is already in place)

**Comment by miketaylr** [comment]
* [ ] possible desktop + mobile candidate, will need some testing: https://bugzilla.mozilla.org/show_bug.cgi?id=1243568

**Comment by ksy36** [comment]
mobile candidate: https://github.com/webcompat/web-bugs/issues/34760
(has been fixed by the site)

**Comment by ksy36** [comment]
- [ ]  mobile + desktop candidate: https://github.com/webcompat/web-bugs/issues/36693

**Comment by ksy36** [comment]
we could potentially add an override here as well, though it requires some testing
mobile https://github.com/webcompat/web-bugs/issues/35163

(this will be fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1574223)

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/36576

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/36951

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/37139

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/15467

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/25384

**Comment by ksy36** [comment]
mobile candidate https://github.com/webcompat/web-bugs/issues/31248
(this is fixed)

**Comment by ksy36** [comment]
desktop + mobile candidate https://github.com/webcompat/web-bugs/issues/32409
(fixed by the site)

**Comment by ksy36** [comment]
- [ ] desktop + mobile candidate https://github.com/webcompat/web-bugs/issues/34969

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/18478

**Comment by ksy36** [comment]
- [ ] desktop candidate https://github.com/webcompat/web-bugs/issues/28742

**Comment by ksy36** [comment]
- [ ] desktop + mobile https://github.com/webcompat/web-bugs/issues/34682

**Comment by ksy36** [comment]
This is on track, I think we're close to about 20 interventions and overrides.

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/33613

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/29867

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/38433

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/24044

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/16363

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/17810

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/28992

**Comment by ksy36** [comment]
- [ ] desktop candidate https://github.com/webcompat/web-bugs/issues/3846

**Comment by miketaylr** [comment]
Update: very close here, perhaps at 22 or 23.

**Comment by ksy36** [comment]
- [ ] desktop candidate https://bugzilla.mozilla.org/show_bug.cgi?id=1577870

**Comment by ksy36** [comment]
- [ ] mobile candidate https://github.com/webcompat/web-bugs/issues/39057

**Comment by ksy36** [comment]
- [ ] mobile + desktop https://github.com/webcompat/web-bugs/issues/35022
